---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis
    author: kumari
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis
    spec:
      containers:
        - name: redisDB
          image: redis
...
